#' @title Displays ternary plot for tissue classes
#' @description Display ternary plot of ICV for MR segmentations with tissue classes.
#' @details Input data frame generated by regr.vol() to create a animated
#' ternary plot for ICA for tissue classes.
#' @param tcvoldf A data frame generated by regr.vol().
#' @return Animated ternary plot
#' @export
tcvoltern <- function(tcvoldf) {
  tcvoldf <- tcvoldf%>%
    filter(norm=='regr_ICV')%>%
    select(-rnum, -label_id, -norm)%>%
    pivot_longer(cols=starts_with('n'),
                 names_to = c('pid', 'time_points'),
                 names_sep = '_', values_to = 'vol_mm3',
                 values_drop_na = TRUE)%>%
    mutate(label_name=substr(R575.uniq.name, 1,
                             nchar(R575.uniq.name)-nchar(class.name)))%>%
    select(class.name, label_name, pid, vol_mm3)%>%
    filter(class.name%in%c('CSF','GM','WM'))%>%
    pivot_wider(names_from = 'class.name', values_from = 'vol_mm3')%>%
    mutate(Tot=CSF+GM+WM, `%CSF`=CSF/Tot*100, `%GM`=GM/Tot*100,
           `%WM`=WM/Tot*100)

  plot_ly(tcvoldf, a = ~CSF, b = ~GM, c = ~WM, frame=~pid,
          type = "scatterternary", color = ~label_name,
          text = ~paste('CSF:',sep='', round(`%CSF`,1),'%',
                        '<br>GM:',
                        round(`%GM`,1),'%', '<br>WM:',
                        round(`%WM`,1),'%','<br>Label name:', label_name))%>%
    layout(
      ternary=list(aaxis=list(title='CSF'),
                   baxis = list(title='GM'),
                   caxis = list(title='WM')))%>%
    animation_slider(currentvalue = list(prefix = "pid:",
                                         font = list(color="red")))%>%
    animation_opts(2000, redraw = FALSE)
}

